// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57VBBSCw8C7LWk5tko3G7QbSvdDqhnUA',
    appId: '1:38106120261:web:4d234f76cca7712282232c',
    messagingSenderId: '38106120261',
    projectId: 'chattingbin-14523',
    authDomain: 'chattingbin-14523.firebaseapp.com',
    databaseURL: 'https://chattingbin-14523-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chattingbin-14523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Z4JbfxUTmVP8jf_NIKyWTUHjTaYq6vs',
    appId: '1:38106120261:android:917b7f3fa9f61e2382232c',
    messagingSenderId: '38106120261',
    projectId: 'chattingbin-14523',
    databaseURL: 'https://chattingbin-14523-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chattingbin-14523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMETmS0H-Ou-8_jnTwrLTQmmPbfeQI7s',
    appId: '1:38106120261:ios:275860c018c4d65982232c',
    messagingSenderId: '38106120261',
    projectId: 'chattingbin-14523',
    databaseURL: 'https://chattingbin-14523-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chattingbin-14523.firebasestorage.app',
    androidClientId: '38106120261-7njj9ug98r393mb5hm5rv35mn4vlklvo.apps.googleusercontent.com',
    iosClientId: '38106120261-o93rbhkjjo1ql2oiqq61ftsqgtgb8usm.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminAmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiMETmS0H-Ou-8_jnTwrLTQmmPbfeQI7s',
    appId: '1:38106120261:ios:275860c018c4d65982232c',
    messagingSenderId: '38106120261',
    projectId: 'chattingbin-14523',
    databaseURL: 'https://chattingbin-14523-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chattingbin-14523.firebasestorage.app',
    androidClientId: '38106120261-7njj9ug98r393mb5hm5rv35mn4vlklvo.apps.googleusercontent.com',
    iosClientId: '38106120261-o93rbhkjjo1ql2oiqq61ftsqgtgb8usm.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminAmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB57VBBSCw8C7LWk5tko3G7QbSvdDqhnUA',
    appId: '1:38106120261:web:2f3a7a91df5bd01b82232c',
    messagingSenderId: '38106120261',
    projectId: 'chattingbin-14523',
    authDomain: 'chattingbin-14523.firebaseapp.com',
    databaseURL: 'https://chattingbin-14523-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chattingbin-14523.firebasestorage.app',
  );
}
